version: '2'

services:
  wordpress-db1:
    container_name: wordpress-db1
    image: "mysql:5.7.17"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress

  wordpress-web1:
    container_name: wordpress-web1
    image: "nginx:1.10.2"
    restart: always
    ports:
      - "40021:80"
    volumes:
      - /home/alexis/mydocker/dockerize-wordpress/nginx/conf.d/wordpress.conf:/etc/nginx/conf.d/default.conf
      - /home/alexis/mydocker/dockerize-wordpress/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/alexis/mydocker/wordpress-project/wordpress:/usr/share/nginx/html
    depends_on:
      - wordpress-db1

  wordpress-php1:
    container_name: wordpress-php1
    image: "php:7.1.2-fpm"
    restart: always
    volumes:
      - /home/alexis/mydocker/wordpress-project/wordpress:/usr/share/nginx/html
    depends_on:
      - wordpress-web1
